/**
 * Directory layout for game-server instances and managed runtimes, plus the ONE
 * function that turns a module-supplied RelPath into an absolute path.
 *
 * Everything lives under userData, never in a user-chosen location. That is a
 * deliberate simplification with a security payoff: because no instance path
 * ever originates outside this module, containment reduces to "resolve under a
 * root we own", and the elevated-firewall path validation that already guards
 * renderer-supplied .exe paths is satisfied for free — the java.exe we point a
 * firewall rule at is one WE installed, not one the user picked.
 *
 *   <userData>/servers/<instanceId>/instance.json   metadata (module, ref, config)
 *   <userData>/servers/<instanceId>/root/           the process working directory
 *   <userData>/servers/<instanceId>/logs/           rotated console logs
 *   <userData>/servers/<instanceId>/content/        hash-addressed synced content
 *   <userData>/runtimes/<id>-<major>/               managed JREs etc.
 *   <userData>/cache/gameserver/                    catalog responses
 *   <userData>/servers/.import/<stagingId>/         user-supplied files, pre-commit
 */
import { app } from 'electron';
import path from 'path';
import fs from 'fs';
import { isSafeRelPath } from '../../shared/gameserver-core';
import type { RelPath, RuntimeRef } from '../../shared/gameserver-types';

/** Instance ids are generated by us (uuid v4, hyphens stripped); this is the
 *  gate that keeps a corrupted store from turning one into a path fragment. */
const INSTANCE_ID = /^[0-9a-f]{8,40}$/;

export function isValidInstanceId(id: unknown): id is string {
  return typeof id === 'string' && INSTANCE_ID.test(id);
}

export function serversRoot(): string {
  return path.join(app.getPath('userData'), 'servers');
}

export function runtimesRoot(): string {
  return path.join(app.getPath('userData'), 'runtimes');
}

export function catalogCacheDir(): string {
  return path.join(app.getPath('userData'), 'cache', 'gameserver');
}

export interface InstancePaths {
  base: string;
  /** The process working directory — where the jar, world and mods live. */
  root: string;
  logs: string;
  content: string;
  meta: string;
}

export function instancePaths(instanceId: string): InstancePaths {
  if (!isValidInstanceId(instanceId)) throw new Error(`invalid instanceId: ${String(instanceId)}`);
  const base = path.join(serversRoot(), instanceId);
  return {
    base,
    root: path.join(base, 'root'),
    logs: path.join(base, 'logs'),
    content: path.join(base, 'content'),
    meta: path.join(base, 'instance.json'),
  };
}

export function runtimeDir(ref: RuntimeRef): string {
  if (!/^[a-z][a-z0-9-]{0,15}$/.test(ref.id) || !Number.isInteger(ref.major) || ref.major < 1 || ref.major > 999) {
    throw new Error(`invalid runtime ref: ${JSON.stringify(ref)}`);
  }
  return path.join(runtimesRoot(), `${ref.id}-${ref.major}`);
}

/**
 * Resolve a module-supplied RelPath under a root we own.
 *
 * Two independent checks, and both are load-bearing. isSafeRelPath is the
 * syntactic gate (no traversal, no drive, no reserved name). The prefix check
 * afterwards is the semantic one: it catches anything the first check could not
 * see, including a root that is itself a symlink and future edits that relax the
 * pattern. Belt and braces on a path that reaches the filesystem is cheap.
 */
export function resolveUnder(root: string, rel: RelPath): string {
  const gate = isSafeRelPath(rel);
  if (!gate.ok) throw new Error(`unsafe relative path (${gate.reason}): ${String(rel)}`);
  const abs = path.resolve(root, gate.path);
  const rootResolved = path.resolve(root);
  if (abs !== rootResolved && !abs.startsWith(rootResolved + path.sep)) {
    throw new Error(`path escapes its root: ${String(rel)}`);
  }
  return abs;
}

export function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

/** Create the full skeleton for a new instance. */
export function ensureInstanceDirs(instanceId: string): InstancePaths {
  const p = instancePaths(instanceId);
  for (const dir of [p.base, p.root, p.logs, p.content]) ensureDir(dir);
  return p;
}

/**
 * Remove an instance directory tree. Guarded by the id pattern above so this
 * can never be pointed at an arbitrary directory.
 *
 * `maxRetries` is what makes this survivable on Windows: a console log stream
 * that has just been closed, or a Java process that has just exited, can still
 * hold a handle for a few dozen milliseconds, and Node's default single-shot
 * `rmSync` then throws ENOTEMPTY with a path long enough to overflow a toast.
 */
export function removeInstanceDir(instanceId: string): void {
  const p = instancePaths(instanceId);
  if (!fs.existsSync(p.base)) return;
  fs.rmSync(p.base, { recursive: true, force: true, maxRetries: 8, retryDelay: 80 });
}

// ─────────────────────────────────────────────────────────────────────────────
// Import staging
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Where user-supplied server files are unpacked BEFORE an instance exists.
 *
 * A sibling of the instances rather than the OS temp dir, for two reasons that
 * both come down to the same move: committing an import is a `rename`, and rename
 * is only atomic within a filesystem. Staging in %TEMP% on a machine whose
 * userData is on another drive turns "commit the import" into a multi-gigabyte
 * copy that can fail halfway. The leading dot keeps it out of the instance id
 * pattern, so a staging directory can never be mistaken for an instance.
 */
export function importStagingRoot(): string {
  return path.join(serversRoot(), '.import');
}

export function importStagingDir(stagingId: string): string {
  if (!isValidInstanceId(stagingId)) throw new Error(`invalid stagingId: ${String(stagingId)}`);
  return path.join(importStagingRoot(), stagingId);
}

/**
 * Delete every staged import. Called at startup and at shutdown: a staging
 * directory only has meaning inside one create-server dialog, so anything found
 * at boot is the debris of a crash and holding gigabytes for it helps nobody.
 */
export function purgeImportStaging(): void {
  fs.rmSync(importStagingRoot(), { recursive: true, force: true });
}

/**
 * Every file under `dir`, as instance-root-relative '/' paths.
 *
 * Bounded on purpose. A modpack with 40 000 files is real, a zip bomb with four
 * million is also real, and the caller uses this listing to answer a question
 * that the first few thousand entries already answer. `truncated` is returned
 * rather than swallowed so the UI can say the scan was partial.
 */
export function listTree(dir: string, limit = 50_000): { files: RelPath[]; bytes: number; truncated: boolean } {
  const files: RelPath[] = [];
  let bytes = 0;
  let truncated = false;

  const walk = (abs: string, rel: string): void => {
    if (truncated) return;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(abs, { withFileTypes: true });
    } catch {
      return; // unreadable subtree — not fatal to identifying the server
    }
    for (const entry of entries) {
      if (files.length >= limit) { truncated = true; return; }
      const childRel = rel ? `${rel}/${entry.name}` : entry.name;
      // Never follow links: an archive can contain one, and a scan that walks it
      // would report files from outside the staging directory as if they were
      // part of the import.
      if (entry.isSymbolicLink()) continue;
      if (entry.isDirectory()) {
        walk(path.join(abs, entry.name), childRel);
      } else if (entry.isFile()) {
        files.push(childRel);
        try { bytes += fs.statSync(path.join(abs, entry.name)).size; } catch { /* raced */ }
      }
    }
  };

  walk(dir, '');
  return { files, bytes, truncated };
}
